### ISSUE TITLE
Add a new language

### ISSUE THREAD

**Issue by Vanguger** [VPKSoft/ScintillaNET#15]
Hello! Could you add the AutoIt language to the build?

**Comment by VPKSoft** [comment]
It seems that [Scintilla](https://scintilla.org) has supported the language since the year 2004. The lexer just needs to be configured and that is not done in the Scintilla.NET core control library. Perhaps you can make a PR for example the [ScintillaLexers](https://github.com/VPKSoft/ScintillaLexers) library to add a default configuration. The Scintilla component seems to contain the AutoIt3 with constant number value of SCLEX_AU3 = 60 and with a name of "au3".
```cpp
LexerModule lmAU3(SCLEX_AU3, ColouriseAU3Doc, "au3", FoldAU3Doc , AU3WordLists);
```
